### ISSUE TITLE
Changing tabs

### ISSUE THREAD

**Issue by jbsmith731** [jbsmith731/chrome-col#1]
1. Open tab, enable overlay (tab 1)
2. Open new tab, enable overlay (tab 2)
3. Remove overlay (tab 2)
4. Switch back to OG tab (tab 1)
   The checkbox isn't checked but the overlay is still visible. You have to check and uncheck to         remove tab.

**Comment by kylenoble** [comment]
23d5e0973a157a83ffc99e1181132ac117a4dc54
